# Generated by Django 5.2.1 on 2025-06-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RAWGapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('steam_id', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='ID Steam')),
                ('favorite_genre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Любимый жанр')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('games', models.ManyToManyField(blank=True, related_name='games', through='RAWGapi.UserGame', to='RAWGapi.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
