# Generated by Django 5.2.1 on 2025-06-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Любимый жанр'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=20, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='ID Steam'),
        ),
    ]
