# Generated by Django 5.2.1 on 2025-06-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_genre',
        ),
    ]
