# Generated by Django 5.2.1 on 2025-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('logo', models.ImageField(null=True, upload_to='games/')),
                ('metacritic', models.IntegerField(null=True)),
                ('genres', models.ManyToManyField(related_name='genres', to='RAWGapi.genre')),
                ('platforms', models.ManyToManyField(related_name='platforms', to='RAWGapi.platform')),
                ('stores', models.ManyToManyField(related_name='stores', to='RAWGapi.store')),
            ],
        ),
    ]
