# Generated by Django 5.2.1 on 2025-06-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAWGapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(blank=True, null=True, related_name='developers', to='RAWGapi.developer'),
        ),
    ]
