# Generated by Django 5.2.1 on 2025-06-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAWGapi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.CharField(null=True),
        ),
    ]
