# Generated by Django 5.2.1 on 2025-06-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAWGapi', '0002_developer_game_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='developer',
            new_name='developers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
    ]
