# Generated by Django 5.2.1 on 2025-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAWGapi', '0003_rename_developer_game_developers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
