# Generated by Django 5.2.1 on 2025-06-08 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAWGapi', '0003_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='user_raiting',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
