# Generated by Django 5.2.1 on 2025-06-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAWGapi', '0004_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
