# Generated by Django 5.2.1 on 2025-06-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAWGapi', '0004_alter_usergame_user_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='games', to='RAWGapi.developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='RAWGapi.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='games', to='RAWGapi.platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stores',
            field=models.ManyToManyField(related_name='games', to='RAWGapi.store'),
        ),
    ]
