# Generated by Django 5.2.1 on 2025-06-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RAWGapi', '0005_alter_game_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
